### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by Zdobnov** [caines1989/telling-the-time-in-different-locations#1]
Yo)
Looks really good, but we can make it brilliant!
1) all files in a one folder is not good. Let's save index.html where it is, but css will go to the styles folder, and js -> script folder. It will make sctructure better.
2) you're calling `setInterval(setgmtclock, 1000)` before declaring setgmtclock function. One day it will cause funny bugs))) call function only after declaration;
3) Main problem which doesn't allow the app to work normally: `querySelector` - selects only ONE element, not all, therefore if you give this data prop to other hands - they still don't wanna work. You need to use `querySelectAll`, but in this case this function will return you an array, not one element, and we need to maintain these array elements one by one.
My implementation:
```
const hourHand = document.querySelectorAll('[data-hour-hand]')
const minuteHand = document.querySelectorAll('[data-minute-hand]')
const secondHand = document.querySelectorAll('[data-second-hand]')

console.log(hourHand)


function setgmtclock(index) {
  const currentDate = new Date()
  const secondsRatio = (currentDate.getSeconds()) / 60
  const minutesRatio = (secondsRatio + currentDate.getMinutes()) / 60
  const hoursRatio = (minutesRatio + currentDate.getHours()) / 12
  setRotation(secondHand[index], secondsRatio)
  setRotation(minuteHand[index], minutesRatio)
  setRotation(hourHand[index], hoursRatio)
}


function setRotation(element, rotationRatio) {
    element.style.setProperty('--rotation', rotationRatio * 360)
}

const timeZones = ['gmt', 'cet', 'est', 'jst'];
timeZones.forEach((item, index) => {
  setgmtclock(index);
  setInterval(() => setgmtclock(index), 1000);
});
```

**Comment by caines1989** [comment]
Wow organising the files into folders makes it 100% better for structure. thank you for the tip. now have all the clocks working but of course, I will have to get them set up for different timezones and not all working on

onto the next issue of setting up the clocks for different timezones relating to jst, cet, est, gmt zones.
